In [16]:
import kagglehub
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

path = kagglehub.dataset_download("yamaerenay/spotify-dataset-19212020-600k-tracks")

print("Path to dataset files:", path)
df = pd.read_csv(path+"/tracks.csv")

Path to dataset files: /Users/glycerol/.cache/kagglehub/datasets/yamaerenay/spotify-dataset-19212020-600k-tracks/versions/1

In [17]:

def convert_dates(dataframe):
    dataframe["release_date"] = pd.to_datetime(dataframe["release_date"],errors = "coerce")   
    return dataframe

def filter_years(dataframe, start, end):
    mask = (dataframe["release_date"].dt.year >= start) & (dataframe["release_date"].dt.year <= end)
    dataframe = dataframe.loc[mask]
    return dataframe
def summarize_yearly_counts(dataframe):
    dataframe["Year"] = dataframe["release_date"].dt.year
    return dataframe.sort_values(["popularity","Year"],ascending = False).reset_index(drop = True)

df = convert_dates(df)
df = filter_years(df,1922,2020) #can change this range
df = summarize_yearly_counts(df)
print(df.columns)
print(df.shape)
df.head()

Index(['id', 'name', 'popularity', 'duration_ms', 'explicit', 'artists',
       'id_artists', 'release_date', 'danceability', 'energy', 'key',
       'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness',
       'liveness', 'valence', 'tempo', 'time_signature', 'Year'],
      dtype='str')
(441799, 21)

,id,name,popularity,duration_ms,explicit,artists,id_artists,release_date,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,Year
0,5QO79kh1waicV47BqGRL3g,Save Your Tears,97,215627,1,['The Weeknd'],['1Xyo4u8uXC1ZmMpatF05PJ'],2020-03-20,0.680,0.826,...,-5.487,1,0.0309,0.02120,0.000012,0.5430,0.644,118.051,4,2020
1,6tDDoYIxWvMLTdKpjFkc1B,telepatía,97,160191,0,['Kali Uchis'],['1U1el3k54VvEUzo3ybLPlM'],2020-12-04,0.653,0.524,...,-9.016,0,0.0502,0.11200,0.000000,0.2030,0.553,83.970,4,2020
2,0VjIjW4GlUZAMYd2vXMi3b,Blinding Lights,96,200040,0,['The Weeknd'],['1Xyo4u8uXC1ZmMpatF05PJ'],2020-03-20,0.514,0.730,...,-5.934,1,0.0598,0.00146,0.000095,0.0897,0.334,171.005,4,2020
3,6f3Slt0GbA2bPZlz0aIFXN,The Business,95,164000,0,['Tiësto'],['2o5jDhtHVPhrJdv3cEQ99Z'],2020-09-16,0.798,0.620,...,-7.079,0,0.2320,0.41400,0.019200,0.1120,0.235,120.031,4,2020
4,3FAJ6O0NOHQV8Mc5Ri6ENp,Heartbreak Anniversary,94,198371,0,['Giveon'],['4fxd5Ee7UefO4CUXgwJ7IP'],2020-03-27,0.449,0.465,...,-8.964,1,0.0791,0.52400,0.000001,0.3030,0.543,89.087,3,2020

In [18]:
df_sub = df[['popularity', 'duration_ms','danceability', 'energy','loudness', 'speechiness', 'valence', 'tempo', 'Year']]
df_n = df_sub.groupby("Year",as_index = False).mean() #mean of yearly mean
df_n

,Year,popularity,duration_ms,danceability,energy,loudness,speechiness,valence,tempo
0,1922,0.043478,148401.478261,0.546116,0.218644,-19.722587,0.445028,0.513196,96.474225
1,1923,0.002481,141065.491315,0.662303,0.238749,-19.350769,0.845367,0.688931,103.226385
2,1924,0.006849,176537.143836,0.511795,0.318524,-15.554370,0.129562,0.620766,120.841192
3,1925,0.006289,209472.088050,0.618170,0.176867,-19.221796,0.688627,0.546887,101.280097
4,1926,0.378016,181300.780161,0.544646,0.299197,-14.408121,0.083245,0.617978,114.463853
...,...,...,...,...,...,...,...,...,...
94,2016,39.319568,230029.836462,0.603749,0.659878,-7.253729,0.094928,0.493718,121.429918
95,2017,42.241053,229771.369459,0.625046,0.659544,-7.217948,0.100523,0.493963,121.322002
96,2018,42.131369,220806.222620,0.634320,0.652431,-7.386089,0.108299,0.483001,121.711563
97,2019,44.919358,216815.878826,0.649786,0.637052,-7.433780,0.111213,0.494201,122.006566
98,2020,44.686948,203920.337304,0.657129,0.639669,-7.533985,0.112279,0.501712,122.364673

In [19]:
fig = px.line(df_n, x = "Year",y = "popularity")
fig

In [3]:
from jinja2 import Template

In [22]:
input_html = "./template.html"
output_html = "./index.html"

In [23]:
plotly_fig = {"fig":fig.to_html(full_html=False)}

with open(output_html, "w", encoding="utf-8") as output_file:
    with open(input_html) as template:
        j2_template = Template(template.read())
        output_file.write(j2_template.render(plotly_fig))